#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp $TMPDIR/resource-check.XXXXXX)
cat > "$payload" <&0

version=$(jq -r '.version.version // empty' < "$payload")

source_project=$(jq -r '.source.project // empty' < "$payload")
if [[ "${source_project}X" == "X" ]]; then
  >&2 echo "Source parameter 'project' is missing"
  exit 1
fi

curl -sf https://releases.hashicorp.com/${source_project}/index.json > /dev/null || (
  >&2 echo "Unknown hashicorp project '$source_project'"
  exit 1
)
>&2 echo "Looking up versions of '${source_project}'"
latest_version=$(curl -s https://releases.hashicorp.com/${source_project}/index.json | jq -r '.versions | keys | .[-1]')

>&2 echo "Latest version $latest_version"

jq -n --arg version "${latest_version}" '[{ version: $version }]' >&3
