#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

payload=$(mktemp $TMPDIR/resource-check.XXXXXX)
cat > "$payload" <&0

version=$(jq -r '.version.version // empty' < "$payload")
if [[ "${version}X" == "X" ]]; then
  >&2 echo "Version info 'version' is missing"
  exit 1
fi

source_project=$(jq -r '.source.project // empty' < "$payload")
if [[ "${source_project}X" == "X" ]]; then
  >&2 echo "Source parameter 'project' is missing"
  exit 1
fi

params_regexp=$(jq -r '.params.regexp // empty' < "$payload")

curl -sf https://releases.hashicorp.com/${source_project}/index.json > /dev/null || (
  >&2 echo "Unknown hashicorp project '$source_project'"
  exit 1
)

>&2 echo "Fetching assets ${source_project} v${version}"
cd $destination
echo "$version" > version
echo "$source_project" > project

build_urls=$(curl -s https://releases.hashicorp.com/${source_project}/index.json | jq -r ".versions[\"${version}\"].builds[].url")
if [[ ! -z $params_regexp ]]; then
  build_urls=$(echo "${build_urls}" | grep ${params_regexp})
fi
echo "$build_urls" | xargs -L1 curl -O
